import numpy as np
import matplotlib.pyplot as plt

# Load C++ output (assuming 'burgers_output_cpp.dat' was generated by the C++ code)
cpp_data = np.loadtxt('burgers_output_cpp.dat')  # Read C++ output
x_cpp = cpp_data[:, 0]  # Positions (from the first column)
u_cpp = cpp_data[:, 1]  # Velocities (from the second column)

# Load Python output (assuming 'burgers_output_python.dat' was generated by the Python code)
python_data = np.loadtxt('burgers_output_python.dat')  # Read Python output
x_python = python_data[:, 0]  # Positions
u_python = python_data[:, 1]  # Velocities

# Plot both outputs on the same graph
plt.plot(x_cpp, u_cpp, label="C++", linestyle='-', color='blue')
plt.plot(x_python, u_python, label="Python", linestyle='--', color='red')

# Adding labels and title
plt.title("Comparison of Burgers' Equation (C++ vs Python)")
plt.xlabel('Position (x)')
plt.ylabel('Velocity (u)')
plt.legend()

# Save the plot to a file in the same directory
plt.savefig('comparison_plot.png', dpi=300)

# Optionally, show the plot
plt.show()